//python3 exportCPPCodeFromJSONConfiguration.py --front body --config dataset/body_configuration.json

#pragma once

#include <iostream>
#include <math.h>
#include <vector>

static const char * mocapNET_body_front[] = 
{
 "2DX_hip", //0 
 "2DY_hip", //1 
 "visible_hip", //2 
 "2DX_abdomen", //3 
 "2DY_abdomen", //4 
 "visible_abdomen", //5 
 "2DX_chest", //6 
 "2DY_chest", //7 
 "visible_chest", //8 
 "2DX_neck", //9 
 "2DY_neck", //10 
 "visible_neck", //11 
 "2DX_head", //12 
 "2DY_head", //13 
 "visible_head", //14 
 "2DX_rcollar", //15 
 "2DY_rcollar", //16 
 "visible_rcollar", //17 
 "2DX_rshoulder", //18 
 "2DY_rshoulder", //19 
 "visible_rshoulder", //20 
 "2DX_relbow", //21 
 "2DY_relbow", //22 
 "visible_relbow", //23 
 "2DX_rhand", //24 
 "2DY_rhand", //25 
 "visible_rhand", //26 
 "2DX_lcollar", //27 
 "2DY_lcollar", //28 
 "visible_lcollar", //29 
 "2DX_lshoulder", //30 
 "2DY_lshoulder", //31 
 "visible_lshoulder", //32 
 "2DX_lelbow", //33 
 "2DY_lelbow", //34 
 "visible_lelbow", //35 
 "2DX_lhand", //36 
 "2DY_lhand", //37 
 "visible_lhand", //38 
 "2DX_rhip", //39 
 "2DY_rhip", //40 
 "visible_rhip", //41 
 "2DX_rknee", //42 
 "2DY_rknee", //43 
 "visible_rknee", //44 
 "2DX_rfoot", //45 
 "2DY_rfoot", //46 
 "visible_rfoot", //47 
 "2DX_toe3-2.r", //48 
 "2DY_toe3-2.r", //49 
 "visible_toe3-2.r", //50 
 "2DX_lhip", //51 
 "2DY_lhip", //52 
 "visible_lhip", //53 
 "2DX_lknee", //54 
 "2DY_lknee", //55 
 "visible_lknee", //56 
 "2DX_lfoot", //57 
 "2DY_lfoot", //58 
 "visible_lfoot", //59 
 "2DX_toe3-2.l", //60 
 "2DY_toe3-2.l", //61 
 "visible_toe3-2.l", //62 
 "hipX-hipX", //63 
 "hipY-hipY", //64 
 "hipX-abdomenX", //65 
 "hipY-abdomenY", //66 
 "hipX-chestX", //67 
 "hipY-chestY", //68 
 "hipX-neckX", //69 
 "hipY-neckY", //70 
 "hipX-virtual_hip_x_plus0_3_y_0X", //71 
 "hipY-virtual_hip_x_plus0_3_y_0Y", //72 
 "hipX-rshoulderX", //73 
 "hipY-rshoulderY", //74 
 "hipX-relbowX", //75 
 "hipY-relbowY", //76 
 "hipX-rhandX", //77 
 "hipY-rhandY", //78 
 "hipX-virtual_hip_x_minus_0_3_y_0X", //79 
 "hipY-virtual_hip_x_minus_0_3_y_0Y", //80 
 "hipX-lshoulderX", //81 
 "hipY-lshoulderY", //82 
 "hipX-lelbowX", //83 
 "hipY-lelbowY", //84 
 "hipX-lhandX", //85 
 "hipY-lhandY", //86 
 "hipX-rhipX", //87 
 "hipY-rhipY", //88 
 "hipX-rkneeX", //89 
 "hipY-rkneeY", //90 
 "hipX-rfootX", //91 
 "hipY-rfootY", //92 
 "hipX-lhipX", //93 
 "hipY-lhipY", //94 
 "hipX-lkneeX", //95 
 "hipY-lkneeY", //96 
 "hipX-lfootX", //97 
 "hipY-lfootY", //98 
 "abdomenX-hipX", //99 
 "abdomenY-hipY", //100 
 "abdomenX-abdomenX", //101 
 "abdomenY-abdomenY", //102 
 "abdomenX-chestX", //103 
 "abdomenY-chestY", //104 
 "abdomenX-neckX", //105 
 "abdomenY-neckY", //106 
 "abdomenX-virtual_hip_x_plus0_3_y_0X", //107 
 "abdomenY-virtual_hip_x_plus0_3_y_0Y", //108 
 "abdomenX-rshoulderX", //109 
 "abdomenY-rshoulderY", //110 
 "abdomenX-relbowX", //111 
 "abdomenY-relbowY", //112 
 "abdomenX-rhandX", //113 
 "abdomenY-rhandY", //114 
 "abdomenX-virtual_hip_x_minus_0_3_y_0X", //115 
 "abdomenY-virtual_hip_x_minus_0_3_y_0Y", //116 
 "abdomenX-lshoulderX", //117 
 "abdomenY-lshoulderY", //118 
 "abdomenX-lelbowX", //119 
 "abdomenY-lelbowY", //120 
 "abdomenX-lhandX", //121 
 "abdomenY-lhandY", //122 
 "abdomenX-rhipX", //123 
 "abdomenY-rhipY", //124 
 "abdomenX-rkneeX", //125 
 "abdomenY-rkneeY", //126 
 "abdomenX-rfootX", //127 
 "abdomenY-rfootY", //128 
 "abdomenX-lhipX", //129 
 "abdomenY-lhipY", //130 
 "abdomenX-lkneeX", //131 
 "abdomenY-lkneeY", //132 
 "abdomenX-lfootX", //133 
 "abdomenY-lfootY", //134 
 "chestX-hipX", //135 
 "chestY-hipY", //136 
 "chestX-abdomenX", //137 
 "chestY-abdomenY", //138 
 "chestX-chestX", //139 
 "chestY-chestY", //140 
 "chestX-neckX", //141 
 "chestY-neckY", //142 
 "chestX-virtual_hip_x_plus0_3_y_0X", //143 
 "chestY-virtual_hip_x_plus0_3_y_0Y", //144 
 "chestX-rshoulderX", //145 
 "chestY-rshoulderY", //146 
 "chestX-relbowX", //147 
 "chestY-relbowY", //148 
 "chestX-rhandX", //149 
 "chestY-rhandY", //150 
 "chestX-virtual_hip_x_minus_0_3_y_0X", //151 
 "chestY-virtual_hip_x_minus_0_3_y_0Y", //152 
 "chestX-lshoulderX", //153 
 "chestY-lshoulderY", //154 
 "chestX-lelbowX", //155 
 "chestY-lelbowY", //156 
 "chestX-lhandX", //157 
 "chestY-lhandY", //158 
 "chestX-rhipX", //159 
 "chestY-rhipY", //160 
 "chestX-rkneeX", //161 
 "chestY-rkneeY", //162 
 "chestX-rfootX", //163 
 "chestY-rfootY", //164 
 "chestX-lhipX", //165 
 "chestY-lhipY", //166 
 "chestX-lkneeX", //167 
 "chestY-lkneeY", //168 
 "chestX-lfootX", //169 
 "chestY-lfootY", //170 
 "neckX-hipX", //171 
 "neckY-hipY", //172 
 "neckX-abdomenX", //173 
 "neckY-abdomenY", //174 
 "neckX-chestX", //175 
 "neckY-chestY", //176 
 "neckX-neckX", //177 
 "neckY-neckY", //178 
 "neckX-virtual_hip_x_plus0_3_y_0X", //179 
 "neckY-virtual_hip_x_plus0_3_y_0Y", //180 
 "neckX-rshoulderX", //181 
 "neckY-rshoulderY", //182 
 "neckX-relbowX", //183 
 "neckY-relbowY", //184 
 "neckX-rhandX", //185 
 "neckY-rhandY", //186 
 "neckX-virtual_hip_x_minus_0_3_y_0X", //187 
 "neckY-virtual_hip_x_minus_0_3_y_0Y", //188 
 "neckX-lshoulderX", //189 
 "neckY-lshoulderY", //190 
 "neckX-lelbowX", //191 
 "neckY-lelbowY", //192 
 "neckX-lhandX", //193 
 "neckY-lhandY", //194 
 "neckX-rhipX", //195 
 "neckY-rhipY", //196 
 "neckX-rkneeX", //197 
 "neckY-rkneeY", //198 
 "neckX-rfootX", //199 
 "neckY-rfootY", //200 
 "neckX-lhipX", //201 
 "neckY-lhipY", //202 
 "neckX-lkneeX", //203 
 "neckY-lkneeY", //204 
 "neckX-lfootX", //205 
 "neckY-lfootY", //206 
 "virtual_hip_x_plus0_3_y_0X-hipX", //207 
 "virtual_hip_x_plus0_3_y_0Y-hipY", //208 
 "virtual_hip_x_plus0_3_y_0X-abdomenX", //209 
 "virtual_hip_x_plus0_3_y_0Y-abdomenY", //210 
 "virtual_hip_x_plus0_3_y_0X-chestX", //211 
 "virtual_hip_x_plus0_3_y_0Y-chestY", //212 
 "virtual_hip_x_plus0_3_y_0X-neckX", //213 
 "virtual_hip_x_plus0_3_y_0Y-neckY", //214 
 "virtual_hip_x_plus0_3_y_0X-virtual_hip_x_plus0_3_y_0X", //215 
 "virtual_hip_x_plus0_3_y_0Y-virtual_hip_x_plus0_3_y_0Y", //216 
 "virtual_hip_x_plus0_3_y_0X-rshoulderX", //217 
 "virtual_hip_x_plus0_3_y_0Y-rshoulderY", //218 
 "virtual_hip_x_plus0_3_y_0X-relbowX", //219 
 "virtual_hip_x_plus0_3_y_0Y-relbowY", //220 
 "virtual_hip_x_plus0_3_y_0X-rhandX", //221 
 "virtual_hip_x_plus0_3_y_0Y-rhandY", //222 
 "virtual_hip_x_plus0_3_y_0X-virtual_hip_x_minus_0_3_y_0X", //223 
 "virtual_hip_x_plus0_3_y_0Y-virtual_hip_x_minus_0_3_y_0Y", //224 
 "virtual_hip_x_plus0_3_y_0X-lshoulderX", //225 
 "virtual_hip_x_plus0_3_y_0Y-lshoulderY", //226 
 "virtual_hip_x_plus0_3_y_0X-lelbowX", //227 
 "virtual_hip_x_plus0_3_y_0Y-lelbowY", //228 
 "virtual_hip_x_plus0_3_y_0X-lhandX", //229 
 "virtual_hip_x_plus0_3_y_0Y-lhandY", //230 
 "virtual_hip_x_plus0_3_y_0X-rhipX", //231 
 "virtual_hip_x_plus0_3_y_0Y-rhipY", //232 
 "virtual_hip_x_plus0_3_y_0X-rkneeX", //233 
 "virtual_hip_x_plus0_3_y_0Y-rkneeY", //234 
 "virtual_hip_x_plus0_3_y_0X-rfootX", //235 
 "virtual_hip_x_plus0_3_y_0Y-rfootY", //236 
 "virtual_hip_x_plus0_3_y_0X-lhipX", //237 
 "virtual_hip_x_plus0_3_y_0Y-lhipY", //238 
 "virtual_hip_x_plus0_3_y_0X-lkneeX", //239 
 "virtual_hip_x_plus0_3_y_0Y-lkneeY", //240 
 "virtual_hip_x_plus0_3_y_0X-lfootX", //241 
 "virtual_hip_x_plus0_3_y_0Y-lfootY", //242 
 "rshoulderX-hipX", //243 
 "rshoulderY-hipY", //244 
 "rshoulderX-abdomenX", //245 
 "rshoulderY-abdomenY", //246 
 "rshoulderX-chestX", //247 
 "rshoulderY-chestY", //248 
 "rshoulderX-neckX", //249 
 "rshoulderY-neckY", //250 
 "rshoulderX-virtual_hip_x_plus0_3_y_0X", //251 
 "rshoulderY-virtual_hip_x_plus0_3_y_0Y", //252 
 "rshoulderX-rshoulderX", //253 
 "rshoulderY-rshoulderY", //254 
 "rshoulderX-relbowX", //255 
 "rshoulderY-relbowY", //256 
 "rshoulderX-rhandX", //257 
 "rshoulderY-rhandY", //258 
 "rshoulderX-virtual_hip_x_minus_0_3_y_0X", //259 
 "rshoulderY-virtual_hip_x_minus_0_3_y_0Y", //260 
 "rshoulderX-lshoulderX", //261 
 "rshoulderY-lshoulderY", //262 
 "rshoulderX-lelbowX", //263 
 "rshoulderY-lelbowY", //264 
 "rshoulderX-lhandX", //265 
 "rshoulderY-lhandY", //266 
 "rshoulderX-rhipX", //267 
 "rshoulderY-rhipY", //268 
 "rshoulderX-rkneeX", //269 
 "rshoulderY-rkneeY", //270 
 "rshoulderX-rfootX", //271 
 "rshoulderY-rfootY", //272 
 "rshoulderX-lhipX", //273 
 "rshoulderY-lhipY", //274 
 "rshoulderX-lkneeX", //275 
 "rshoulderY-lkneeY", //276 
 "rshoulderX-lfootX", //277 
 "rshoulderY-lfootY", //278 
 "relbowX-hipX", //279 
 "relbowY-hipY", //280 
 "relbowX-abdomenX", //281 
 "relbowY-abdomenY", //282 
 "relbowX-chestX", //283 
 "relbowY-chestY", //284 
 "relbowX-neckX", //285 
 "relbowY-neckY", //286 
 "relbowX-virtual_hip_x_plus0_3_y_0X", //287 
 "relbowY-virtual_hip_x_plus0_3_y_0Y", //288 
 "relbowX-rshoulderX", //289 
 "relbowY-rshoulderY", //290 
 "relbowX-relbowX", //291 
 "relbowY-relbowY", //292 
 "relbowX-rhandX", //293 
 "relbowY-rhandY", //294 
 "relbowX-virtual_hip_x_minus_0_3_y_0X", //295 
 "relbowY-virtual_hip_x_minus_0_3_y_0Y", //296 
 "relbowX-lshoulderX", //297 
 "relbowY-lshoulderY", //298 
 "relbowX-lelbowX", //299 
 "relbowY-lelbowY", //300 
 "relbowX-lhandX", //301 
 "relbowY-lhandY", //302 
 "relbowX-rhipX", //303 
 "relbowY-rhipY", //304 
 "relbowX-rkneeX", //305 
 "relbowY-rkneeY", //306 
 "relbowX-rfootX", //307 
 "relbowY-rfootY", //308 
 "relbowX-lhipX", //309 
 "relbowY-lhipY", //310 
 "relbowX-lkneeX", //311 
 "relbowY-lkneeY", //312 
 "relbowX-lfootX", //313 
 "relbowY-lfootY", //314 
 "rhandX-hipX", //315 
 "rhandY-hipY", //316 
 "rhandX-abdomenX", //317 
 "rhandY-abdomenY", //318 
 "rhandX-chestX", //319 
 "rhandY-chestY", //320 
 "rhandX-neckX", //321 
 "rhandY-neckY", //322 
 "rhandX-virtual_hip_x_plus0_3_y_0X", //323 
 "rhandY-virtual_hip_x_plus0_3_y_0Y", //324 
 "rhandX-rshoulderX", //325 
 "rhandY-rshoulderY", //326 
 "rhandX-relbowX", //327 
 "rhandY-relbowY", //328 
 "rhandX-rhandX", //329 
 "rhandY-rhandY", //330 
 "rhandX-virtual_hip_x_minus_0_3_y_0X", //331 
 "rhandY-virtual_hip_x_minus_0_3_y_0Y", //332 
 "rhandX-lshoulderX", //333 
 "rhandY-lshoulderY", //334 
 "rhandX-lelbowX", //335 
 "rhandY-lelbowY", //336 
 "rhandX-lhandX", //337 
 "rhandY-lhandY", //338 
 "rhandX-rhipX", //339 
 "rhandY-rhipY", //340 
 "rhandX-rkneeX", //341 
 "rhandY-rkneeY", //342 
 "rhandX-rfootX", //343 
 "rhandY-rfootY", //344 
 "rhandX-lhipX", //345 
 "rhandY-lhipY", //346 
 "rhandX-lkneeX", //347 
 "rhandY-lkneeY", //348 
 "rhandX-lfootX", //349 
 "rhandY-lfootY", //350 
 "virtual_hip_x_minus_0_3_y_0X-hipX", //351 
 "virtual_hip_x_minus_0_3_y_0Y-hipY", //352 
 "virtual_hip_x_minus_0_3_y_0X-abdomenX", //353 
 "virtual_hip_x_minus_0_3_y_0Y-abdomenY", //354 
 "virtual_hip_x_minus_0_3_y_0X-chestX", //355 
 "virtual_hip_x_minus_0_3_y_0Y-chestY", //356 
 "virtual_hip_x_minus_0_3_y_0X-neckX", //357 
 "virtual_hip_x_minus_0_3_y_0Y-neckY", //358 
 "virtual_hip_x_minus_0_3_y_0X-virtual_hip_x_plus0_3_y_0X", //359 
 "virtual_hip_x_minus_0_3_y_0Y-virtual_hip_x_plus0_3_y_0Y", //360 
 "virtual_hip_x_minus_0_3_y_0X-rshoulderX", //361 
 "virtual_hip_x_minus_0_3_y_0Y-rshoulderY", //362 
 "virtual_hip_x_minus_0_3_y_0X-relbowX", //363 
 "virtual_hip_x_minus_0_3_y_0Y-relbowY", //364 
 "virtual_hip_x_minus_0_3_y_0X-rhandX", //365 
 "virtual_hip_x_minus_0_3_y_0Y-rhandY", //366 
 "virtual_hip_x_minus_0_3_y_0X-virtual_hip_x_minus_0_3_y_0X", //367 
 "virtual_hip_x_minus_0_3_y_0Y-virtual_hip_x_minus_0_3_y_0Y", //368 
 "virtual_hip_x_minus_0_3_y_0X-lshoulderX", //369 
 "virtual_hip_x_minus_0_3_y_0Y-lshoulderY", //370 
 "virtual_hip_x_minus_0_3_y_0X-lelbowX", //371 
 "virtual_hip_x_minus_0_3_y_0Y-lelbowY", //372 
 "virtual_hip_x_minus_0_3_y_0X-lhandX", //373 
 "virtual_hip_x_minus_0_3_y_0Y-lhandY", //374 
 "virtual_hip_x_minus_0_3_y_0X-rhipX", //375 
 "virtual_hip_x_minus_0_3_y_0Y-rhipY", //376 
 "virtual_hip_x_minus_0_3_y_0X-rkneeX", //377 
 "virtual_hip_x_minus_0_3_y_0Y-rkneeY", //378 
 "virtual_hip_x_minus_0_3_y_0X-rfootX", //379 
 "virtual_hip_x_minus_0_3_y_0Y-rfootY", //380 
 "virtual_hip_x_minus_0_3_y_0X-lhipX", //381 
 "virtual_hip_x_minus_0_3_y_0Y-lhipY", //382 
 "virtual_hip_x_minus_0_3_y_0X-lkneeX", //383 
 "virtual_hip_x_minus_0_3_y_0Y-lkneeY", //384 
 "virtual_hip_x_minus_0_3_y_0X-lfootX", //385 
 "virtual_hip_x_minus_0_3_y_0Y-lfootY", //386 
 "lshoulderX-hipX", //387 
 "lshoulderY-hipY", //388 
 "lshoulderX-abdomenX", //389 
 "lshoulderY-abdomenY", //390 
 "lshoulderX-chestX", //391 
 "lshoulderY-chestY", //392 
 "lshoulderX-neckX", //393 
 "lshoulderY-neckY", //394 
 "lshoulderX-virtual_hip_x_plus0_3_y_0X", //395 
 "lshoulderY-virtual_hip_x_plus0_3_y_0Y", //396 
 "lshoulderX-rshoulderX", //397 
 "lshoulderY-rshoulderY", //398 
 "lshoulderX-relbowX", //399 
 "lshoulderY-relbowY", //400 
 "lshoulderX-rhandX", //401 
 "lshoulderY-rhandY", //402 
 "lshoulderX-virtual_hip_x_minus_0_3_y_0X", //403 
 "lshoulderY-virtual_hip_x_minus_0_3_y_0Y", //404 
 "lshoulderX-lshoulderX", //405 
 "lshoulderY-lshoulderY", //406 
 "lshoulderX-lelbowX", //407 
 "lshoulderY-lelbowY", //408 
 "lshoulderX-lhandX", //409 
 "lshoulderY-lhandY", //410 
 "lshoulderX-rhipX", //411 
 "lshoulderY-rhipY", //412 
 "lshoulderX-rkneeX", //413 
 "lshoulderY-rkneeY", //414 
 "lshoulderX-rfootX", //415 
 "lshoulderY-rfootY", //416 
 "lshoulderX-lhipX", //417 
 "lshoulderY-lhipY", //418 
 "lshoulderX-lkneeX", //419 
 "lshoulderY-lkneeY", //420 
 "lshoulderX-lfootX", //421 
 "lshoulderY-lfootY", //422 
 "lelbowX-hipX", //423 
 "lelbowY-hipY", //424 
 "lelbowX-abdomenX", //425 
 "lelbowY-abdomenY", //426 
 "lelbowX-chestX", //427 
 "lelbowY-chestY", //428 
 "lelbowX-neckX", //429 
 "lelbowY-neckY", //430 
 "lelbowX-virtual_hip_x_plus0_3_y_0X", //431 
 "lelbowY-virtual_hip_x_plus0_3_y_0Y", //432 
 "lelbowX-rshoulderX", //433 
 "lelbowY-rshoulderY", //434 
 "lelbowX-relbowX", //435 
 "lelbowY-relbowY", //436 
 "lelbowX-rhandX", //437 
 "lelbowY-rhandY", //438 
 "lelbowX-virtual_hip_x_minus_0_3_y_0X", //439 
 "lelbowY-virtual_hip_x_minus_0_3_y_0Y", //440 
 "lelbowX-lshoulderX", //441 
 "lelbowY-lshoulderY", //442 
 "lelbowX-lelbowX", //443 
 "lelbowY-lelbowY", //444 
 "lelbowX-lhandX", //445 
 "lelbowY-lhandY", //446 
 "lelbowX-rhipX", //447 
 "lelbowY-rhipY", //448 
 "lelbowX-rkneeX", //449 
 "lelbowY-rkneeY", //450 
 "lelbowX-rfootX", //451 
 "lelbowY-rfootY", //452 
 "lelbowX-lhipX", //453 
 "lelbowY-lhipY", //454 
 "lelbowX-lkneeX", //455 
 "lelbowY-lkneeY", //456 
 "lelbowX-lfootX", //457 
 "lelbowY-lfootY", //458 
 "lhandX-hipX", //459 
 "lhandY-hipY", //460 
 "lhandX-abdomenX", //461 
 "lhandY-abdomenY", //462 
 "lhandX-chestX", //463 
 "lhandY-chestY", //464 
 "lhandX-neckX", //465 
 "lhandY-neckY", //466 
 "lhandX-virtual_hip_x_plus0_3_y_0X", //467 
 "lhandY-virtual_hip_x_plus0_3_y_0Y", //468 
 "lhandX-rshoulderX", //469 
 "lhandY-rshoulderY", //470 
 "lhandX-relbowX", //471 
 "lhandY-relbowY", //472 
 "lhandX-rhandX", //473 
 "lhandY-rhandY", //474 
 "lhandX-virtual_hip_x_minus_0_3_y_0X", //475 
 "lhandY-virtual_hip_x_minus_0_3_y_0Y", //476 
 "lhandX-lshoulderX", //477 
 "lhandY-lshoulderY", //478 
 "lhandX-lelbowX", //479 
 "lhandY-lelbowY", //480 
 "lhandX-lhandX", //481 
 "lhandY-lhandY", //482 
 "lhandX-rhipX", //483 
 "lhandY-rhipY", //484 
 "lhandX-rkneeX", //485 
 "lhandY-rkneeY", //486 
 "lhandX-rfootX", //487 
 "lhandY-rfootY", //488 
 "lhandX-lhipX", //489 
 "lhandY-lhipY", //490 
 "lhandX-lkneeX", //491 
 "lhandY-lkneeY", //492 
 "lhandX-lfootX", //493 
 "lhandY-lfootY", //494 
 "rhipX-hipX", //495 
 "rhipY-hipY", //496 
 "rhipX-abdomenX", //497 
 "rhipY-abdomenY", //498 
 "rhipX-chestX", //499 
 "rhipY-chestY", //500 
 "rhipX-neckX", //501 
 "rhipY-neckY", //502 
 "rhipX-virtual_hip_x_plus0_3_y_0X", //503 
 "rhipY-virtual_hip_x_plus0_3_y_0Y", //504 
 "rhipX-rshoulderX", //505 
 "rhipY-rshoulderY", //506 
 "rhipX-relbowX", //507 
 "rhipY-relbowY", //508 
 "rhipX-rhandX", //509 
 "rhipY-rhandY", //510 
 "rhipX-virtual_hip_x_minus_0_3_y_0X", //511 
 "rhipY-virtual_hip_x_minus_0_3_y_0Y", //512 
 "rhipX-lshoulderX", //513 
 "rhipY-lshoulderY", //514 
 "rhipX-lelbowX", //515 
 "rhipY-lelbowY", //516 
 "rhipX-lhandX", //517 
 "rhipY-lhandY", //518 
 "rhipX-rhipX", //519 
 "rhipY-rhipY", //520 
 "rhipX-rkneeX", //521 
 "rhipY-rkneeY", //522 
 "rhipX-rfootX", //523 
 "rhipY-rfootY", //524 
 "rhipX-lhipX", //525 
 "rhipY-lhipY", //526 
 "rhipX-lkneeX", //527 
 "rhipY-lkneeY", //528 
 "rhipX-lfootX", //529 
 "rhipY-lfootY", //530 
 "rkneeX-hipX", //531 
 "rkneeY-hipY", //532 
 "rkneeX-abdomenX", //533 
 "rkneeY-abdomenY", //534 
 "rkneeX-chestX", //535 
 "rkneeY-chestY", //536 
 "rkneeX-neckX", //537 
 "rkneeY-neckY", //538 
 "rkneeX-virtual_hip_x_plus0_3_y_0X", //539 
 "rkneeY-virtual_hip_x_plus0_3_y_0Y", //540 
 "rkneeX-rshoulderX", //541 
 "rkneeY-rshoulderY", //542 
 "rkneeX-relbowX", //543 
 "rkneeY-relbowY", //544 
 "rkneeX-rhandX", //545 
 "rkneeY-rhandY", //546 
 "rkneeX-virtual_hip_x_minus_0_3_y_0X", //547 
 "rkneeY-virtual_hip_x_minus_0_3_y_0Y", //548 
 "rkneeX-lshoulderX", //549 
 "rkneeY-lshoulderY", //550 
 "rkneeX-lelbowX", //551 
 "rkneeY-lelbowY", //552 
 "rkneeX-lhandX", //553 
 "rkneeY-lhandY", //554 
 "rkneeX-rhipX", //555 
 "rkneeY-rhipY", //556 
 "rkneeX-rkneeX", //557 
 "rkneeY-rkneeY", //558 
 "rkneeX-rfootX", //559 
 "rkneeY-rfootY", //560 
 "rkneeX-lhipX", //561 
 "rkneeY-lhipY", //562 
 "rkneeX-lkneeX", //563 
 "rkneeY-lkneeY", //564 
 "rkneeX-lfootX", //565 
 "rkneeY-lfootY", //566 
 "rfootX-hipX", //567 
 "rfootY-hipY", //568 
 "rfootX-abdomenX", //569 
 "rfootY-abdomenY", //570 
 "rfootX-chestX", //571 
 "rfootY-chestY", //572 
 "rfootX-neckX", //573 
 "rfootY-neckY", //574 
 "rfootX-virtual_hip_x_plus0_3_y_0X", //575 
 "rfootY-virtual_hip_x_plus0_3_y_0Y", //576 
 "rfootX-rshoulderX", //577 
 "rfootY-rshoulderY", //578 
 "rfootX-relbowX", //579 
 "rfootY-relbowY", //580 
 "rfootX-rhandX", //581 
 "rfootY-rhandY", //582 
 "rfootX-virtual_hip_x_minus_0_3_y_0X", //583 
 "rfootY-virtual_hip_x_minus_0_3_y_0Y", //584 
 "rfootX-lshoulderX", //585 
 "rfootY-lshoulderY", //586 
 "rfootX-lelbowX", //587 
 "rfootY-lelbowY", //588 
 "rfootX-lhandX", //589 
 "rfootY-lhandY", //590 
 "rfootX-rhipX", //591 
 "rfootY-rhipY", //592 
 "rfootX-rkneeX", //593 
 "rfootY-rkneeY", //594 
 "rfootX-rfootX", //595 
 "rfootY-rfootY", //596 
 "rfootX-lhipX", //597 
 "rfootY-lhipY", //598 
 "rfootX-lkneeX", //599 
 "rfootY-lkneeY", //600 
 "rfootX-lfootX", //601 
 "rfootY-lfootY", //602 
 "lhipX-hipX", //603 
 "lhipY-hipY", //604 
 "lhipX-abdomenX", //605 
 "lhipY-abdomenY", //606 
 "lhipX-chestX", //607 
 "lhipY-chestY", //608 
 "lhipX-neckX", //609 
 "lhipY-neckY", //610 
 "lhipX-virtual_hip_x_plus0_3_y_0X", //611 
 "lhipY-virtual_hip_x_plus0_3_y_0Y", //612 
 "lhipX-rshoulderX", //613 
 "lhipY-rshoulderY", //614 
 "lhipX-relbowX", //615 
 "lhipY-relbowY", //616 
 "lhipX-rhandX", //617 
 "lhipY-rhandY", //618 
 "lhipX-virtual_hip_x_minus_0_3_y_0X", //619 
 "lhipY-virtual_hip_x_minus_0_3_y_0Y", //620 
 "lhipX-lshoulderX", //621 
 "lhipY-lshoulderY", //622 
 "lhipX-lelbowX", //623 
 "lhipY-lelbowY", //624 
 "lhipX-lhandX", //625 
 "lhipY-lhandY", //626 
 "lhipX-rhipX", //627 
 "lhipY-rhipY", //628 
 "lhipX-rkneeX", //629 
 "lhipY-rkneeY", //630 
 "lhipX-rfootX", //631 
 "lhipY-rfootY", //632 
 "lhipX-lhipX", //633 
 "lhipY-lhipY", //634 
 "lhipX-lkneeX", //635 
 "lhipY-lkneeY", //636 
 "lhipX-lfootX", //637 
 "lhipY-lfootY", //638 
 "lkneeX-hipX", //639 
 "lkneeY-hipY", //640 
 "lkneeX-abdomenX", //641 
 "lkneeY-abdomenY", //642 
 "lkneeX-chestX", //643 
 "lkneeY-chestY", //644 
 "lkneeX-neckX", //645 
 "lkneeY-neckY", //646 
 "lkneeX-virtual_hip_x_plus0_3_y_0X", //647 
 "lkneeY-virtual_hip_x_plus0_3_y_0Y", //648 
 "lkneeX-rshoulderX", //649 
 "lkneeY-rshoulderY", //650 
 "lkneeX-relbowX", //651 
 "lkneeY-relbowY", //652 
 "lkneeX-rhandX", //653 
 "lkneeY-rhandY", //654 
 "lkneeX-virtual_hip_x_minus_0_3_y_0X", //655 
 "lkneeY-virtual_hip_x_minus_0_3_y_0Y", //656 
 "lkneeX-lshoulderX", //657 
 "lkneeY-lshoulderY", //658 
 "lkneeX-lelbowX", //659 
 "lkneeY-lelbowY", //660 
 "lkneeX-lhandX", //661 
 "lkneeY-lhandY", //662 
 "lkneeX-rhipX", //663 
 "lkneeY-rhipY", //664 
 "lkneeX-rkneeX", //665 
 "lkneeY-rkneeY", //666 
 "lkneeX-rfootX", //667 
 "lkneeY-rfootY", //668 
 "lkneeX-lhipX", //669 
 "lkneeY-lhipY", //670 
 "lkneeX-lkneeX", //671 
 "lkneeY-lkneeY", //672 
 "lkneeX-lfootX", //673 
 "lkneeY-lfootY", //674 
 "lfootX-hipX", //675 
 "lfootY-hipY", //676 
 "lfootX-abdomenX", //677 
 "lfootY-abdomenY", //678 
 "lfootX-chestX", //679 
 "lfootY-chestY", //680 
 "lfootX-neckX", //681 
 "lfootY-neckY", //682 
 "lfootX-virtual_hip_x_plus0_3_y_0X", //683 
 "lfootY-virtual_hip_x_plus0_3_y_0Y", //684 
 "lfootX-rshoulderX", //685 
 "lfootY-rshoulderY", //686 
 "lfootX-relbowX", //687 
 "lfootY-relbowY", //688 
 "lfootX-rhandX", //689 
 "lfootY-rhandY", //690 
 "lfootX-virtual_hip_x_minus_0_3_y_0X", //691 
 "lfootY-virtual_hip_x_minus_0_3_y_0Y", //692 
 "lfootX-lshoulderX", //693 
 "lfootY-lshoulderY", //694 
 "lfootX-lelbowX", //695 
 "lfootY-lelbowY", //696 
 "lfootX-lhandX", //697 
 "lfootY-lhandY", //698 
 "lfootX-rhipX", //699 
 "lfootY-rhipY", //700 
 "lfootX-rkneeX", //701 
 "lfootY-rkneeY", //702 
 "lfootX-rfootX", //703 
 "lfootY-rfootY", //704 
 "lfootX-lhipX", //705 
 "lfootY-lhipY", //706 
 "lfootX-lkneeX", //707 
 "lfootY-lkneeY", //708 
 "lfootX-lfootX", //709 
 "lfootY-lfootY", //710 
 "end"
};
enum mocapNET_body_front 
{
 MNET_BODY_FRONT_IN_2DX_HIP, //0 
 MNET_BODY_FRONT_IN_2DY_HIP, //1 
 MNET_BODY_FRONT_IN_VISIBLE_HIP, //2 
 MNET_BODY_FRONT_IN_2DX_ABDOMEN, //3 
 MNET_BODY_FRONT_IN_2DY_ABDOMEN, //4 
 MNET_BODY_FRONT_IN_VISIBLE_ABDOMEN, //5 
 MNET_BODY_FRONT_IN_2DX_CHEST, //6 
 MNET_BODY_FRONT_IN_2DY_CHEST, //7 
 MNET_BODY_FRONT_IN_VISIBLE_CHEST, //8 
 MNET_BODY_FRONT_IN_2DX_NECK, //9 
 MNET_BODY_FRONT_IN_2DY_NECK, //10 
 MNET_BODY_FRONT_IN_VISIBLE_NECK, //11 
 MNET_BODY_FRONT_IN_2DX_HEAD, //12 
 MNET_BODY_FRONT_IN_2DY_HEAD, //13 
 MNET_BODY_FRONT_IN_VISIBLE_HEAD, //14 
 MNET_BODY_FRONT_IN_2DX_RCOLLAR, //15 
 MNET_BODY_FRONT_IN_2DY_RCOLLAR, //16 
 MNET_BODY_FRONT_IN_VISIBLE_RCOLLAR, //17 
 MNET_BODY_FRONT_IN_2DX_RSHOULDER, //18 
 MNET_BODY_FRONT_IN_2DY_RSHOULDER, //19 
 MNET_BODY_FRONT_IN_VISIBLE_RSHOULDER, //20 
 MNET_BODY_FRONT_IN_2DX_RELBOW, //21 
 MNET_BODY_FRONT_IN_2DY_RELBOW, //22 
 MNET_BODY_FRONT_IN_VISIBLE_RELBOW, //23 
 MNET_BODY_FRONT_IN_2DX_RHAND, //24 
 MNET_BODY_FRONT_IN_2DY_RHAND, //25 
 MNET_BODY_FRONT_IN_VISIBLE_RHAND, //26 
 MNET_BODY_FRONT_IN_2DX_LCOLLAR, //27 
 MNET_BODY_FRONT_IN_2DY_LCOLLAR, //28 
 MNET_BODY_FRONT_IN_VISIBLE_LCOLLAR, //29 
 MNET_BODY_FRONT_IN_2DX_LSHOULDER, //30 
 MNET_BODY_FRONT_IN_2DY_LSHOULDER, //31 
 MNET_BODY_FRONT_IN_VISIBLE_LSHOULDER, //32 
 MNET_BODY_FRONT_IN_2DX_LELBOW, //33 
 MNET_BODY_FRONT_IN_2DY_LELBOW, //34 
 MNET_BODY_FRONT_IN_VISIBLE_LELBOW, //35 
 MNET_BODY_FRONT_IN_2DX_LHAND, //36 
 MNET_BODY_FRONT_IN_2DY_LHAND, //37 
 MNET_BODY_FRONT_IN_VISIBLE_LHAND, //38 
 MNET_BODY_FRONT_IN_2DX_RHIP, //39 
 MNET_BODY_FRONT_IN_2DY_RHIP, //40 
 MNET_BODY_FRONT_IN_VISIBLE_RHIP, //41 
 MNET_BODY_FRONT_IN_2DX_RKNEE, //42 
 MNET_BODY_FRONT_IN_2DY_RKNEE, //43 
 MNET_BODY_FRONT_IN_VISIBLE_RKNEE, //44 
 MNET_BODY_FRONT_IN_2DX_RFOOT, //45 
 MNET_BODY_FRONT_IN_2DY_RFOOT, //46 
 MNET_BODY_FRONT_IN_VISIBLE_RFOOT, //47 
 MNET_BODY_FRONT_IN_2DX_TOE3_2_R, //48 
 MNET_BODY_FRONT_IN_2DY_TOE3_2_R, //49 
 MNET_BODY_FRONT_IN_VISIBLE_TOE3_2_R, //50 
 MNET_BODY_FRONT_IN_2DX_LHIP, //51 
 MNET_BODY_FRONT_IN_2DY_LHIP, //52 
 MNET_BODY_FRONT_IN_VISIBLE_LHIP, //53 
 MNET_BODY_FRONT_IN_2DX_LKNEE, //54 
 MNET_BODY_FRONT_IN_2DY_LKNEE, //55 
 MNET_BODY_FRONT_IN_VISIBLE_LKNEE, //56 
 MNET_BODY_FRONT_IN_2DX_LFOOT, //57 
 MNET_BODY_FRONT_IN_2DY_LFOOT, //58 
 MNET_BODY_FRONT_IN_VISIBLE_LFOOT, //59 
 MNET_BODY_FRONT_IN_2DX_TOE3_2_L, //60 
 MNET_BODY_FRONT_IN_2DY_TOE3_2_L, //61 
 MNET_BODY_FRONT_IN_VISIBLE_TOE3_2_L, //62 
 MNET_BODY_FRONT_IN_HIPX_HIPX, //63 
 MNET_BODY_FRONT_IN_HIPY_HIPY, //64 
 MNET_BODY_FRONT_IN_HIPX_ABDOMENX, //65 
 MNET_BODY_FRONT_IN_HIPY_ABDOMENY, //66 
 MNET_BODY_FRONT_IN_HIPX_CHESTX, //67 
 MNET_BODY_FRONT_IN_HIPY_CHESTY, //68 
 MNET_BODY_FRONT_IN_HIPX_NECKX, //69 
 MNET_BODY_FRONT_IN_HIPY_NECKY, //70 
 MNET_BODY_FRONT_IN_HIPX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //71 
 MNET_BODY_FRONT_IN_HIPY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //72 
 MNET_BODY_FRONT_IN_HIPX_RSHOULDERX, //73 
 MNET_BODY_FRONT_IN_HIPY_RSHOULDERY, //74 
 MNET_BODY_FRONT_IN_HIPX_RELBOWX, //75 
 MNET_BODY_FRONT_IN_HIPY_RELBOWY, //76 
 MNET_BODY_FRONT_IN_HIPX_RHANDX, //77 
 MNET_BODY_FRONT_IN_HIPY_RHANDY, //78 
 MNET_BODY_FRONT_IN_HIPX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //79 
 MNET_BODY_FRONT_IN_HIPY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //80 
 MNET_BODY_FRONT_IN_HIPX_LSHOULDERX, //81 
 MNET_BODY_FRONT_IN_HIPY_LSHOULDERY, //82 
 MNET_BODY_FRONT_IN_HIPX_LELBOWX, //83 
 MNET_BODY_FRONT_IN_HIPY_LELBOWY, //84 
 MNET_BODY_FRONT_IN_HIPX_LHANDX, //85 
 MNET_BODY_FRONT_IN_HIPY_LHANDY, //86 
 MNET_BODY_FRONT_IN_HIPX_RHIPX, //87 
 MNET_BODY_FRONT_IN_HIPY_RHIPY, //88 
 MNET_BODY_FRONT_IN_HIPX_RKNEEX, //89 
 MNET_BODY_FRONT_IN_HIPY_RKNEEY, //90 
 MNET_BODY_FRONT_IN_HIPX_RFOOTX, //91 
 MNET_BODY_FRONT_IN_HIPY_RFOOTY, //92 
 MNET_BODY_FRONT_IN_HIPX_LHIPX, //93 
 MNET_BODY_FRONT_IN_HIPY_LHIPY, //94 
 MNET_BODY_FRONT_IN_HIPX_LKNEEX, //95 
 MNET_BODY_FRONT_IN_HIPY_LKNEEY, //96 
 MNET_BODY_FRONT_IN_HIPX_LFOOTX, //97 
 MNET_BODY_FRONT_IN_HIPY_LFOOTY, //98 
 MNET_BODY_FRONT_IN_ABDOMENX_HIPX, //99 
 MNET_BODY_FRONT_IN_ABDOMENY_HIPY, //100 
 MNET_BODY_FRONT_IN_ABDOMENX_ABDOMENX, //101 
 MNET_BODY_FRONT_IN_ABDOMENY_ABDOMENY, //102 
 MNET_BODY_FRONT_IN_ABDOMENX_CHESTX, //103 
 MNET_BODY_FRONT_IN_ABDOMENY_CHESTY, //104 
 MNET_BODY_FRONT_IN_ABDOMENX_NECKX, //105 
 MNET_BODY_FRONT_IN_ABDOMENY_NECKY, //106 
 MNET_BODY_FRONT_IN_ABDOMENX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //107 
 MNET_BODY_FRONT_IN_ABDOMENY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //108 
 MNET_BODY_FRONT_IN_ABDOMENX_RSHOULDERX, //109 
 MNET_BODY_FRONT_IN_ABDOMENY_RSHOULDERY, //110 
 MNET_BODY_FRONT_IN_ABDOMENX_RELBOWX, //111 
 MNET_BODY_FRONT_IN_ABDOMENY_RELBOWY, //112 
 MNET_BODY_FRONT_IN_ABDOMENX_RHANDX, //113 
 MNET_BODY_FRONT_IN_ABDOMENY_RHANDY, //114 
 MNET_BODY_FRONT_IN_ABDOMENX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //115 
 MNET_BODY_FRONT_IN_ABDOMENY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //116 
 MNET_BODY_FRONT_IN_ABDOMENX_LSHOULDERX, //117 
 MNET_BODY_FRONT_IN_ABDOMENY_LSHOULDERY, //118 
 MNET_BODY_FRONT_IN_ABDOMENX_LELBOWX, //119 
 MNET_BODY_FRONT_IN_ABDOMENY_LELBOWY, //120 
 MNET_BODY_FRONT_IN_ABDOMENX_LHANDX, //121 
 MNET_BODY_FRONT_IN_ABDOMENY_LHANDY, //122 
 MNET_BODY_FRONT_IN_ABDOMENX_RHIPX, //123 
 MNET_BODY_FRONT_IN_ABDOMENY_RHIPY, //124 
 MNET_BODY_FRONT_IN_ABDOMENX_RKNEEX, //125 
 MNET_BODY_FRONT_IN_ABDOMENY_RKNEEY, //126 
 MNET_BODY_FRONT_IN_ABDOMENX_RFOOTX, //127 
 MNET_BODY_FRONT_IN_ABDOMENY_RFOOTY, //128 
 MNET_BODY_FRONT_IN_ABDOMENX_LHIPX, //129 
 MNET_BODY_FRONT_IN_ABDOMENY_LHIPY, //130 
 MNET_BODY_FRONT_IN_ABDOMENX_LKNEEX, //131 
 MNET_BODY_FRONT_IN_ABDOMENY_LKNEEY, //132 
 MNET_BODY_FRONT_IN_ABDOMENX_LFOOTX, //133 
 MNET_BODY_FRONT_IN_ABDOMENY_LFOOTY, //134 
 MNET_BODY_FRONT_IN_CHESTX_HIPX, //135 
 MNET_BODY_FRONT_IN_CHESTY_HIPY, //136 
 MNET_BODY_FRONT_IN_CHESTX_ABDOMENX, //137 
 MNET_BODY_FRONT_IN_CHESTY_ABDOMENY, //138 
 MNET_BODY_FRONT_IN_CHESTX_CHESTX, //139 
 MNET_BODY_FRONT_IN_CHESTY_CHESTY, //140 
 MNET_BODY_FRONT_IN_CHESTX_NECKX, //141 
 MNET_BODY_FRONT_IN_CHESTY_NECKY, //142 
 MNET_BODY_FRONT_IN_CHESTX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //143 
 MNET_BODY_FRONT_IN_CHESTY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //144 
 MNET_BODY_FRONT_IN_CHESTX_RSHOULDERX, //145 
 MNET_BODY_FRONT_IN_CHESTY_RSHOULDERY, //146 
 MNET_BODY_FRONT_IN_CHESTX_RELBOWX, //147 
 MNET_BODY_FRONT_IN_CHESTY_RELBOWY, //148 
 MNET_BODY_FRONT_IN_CHESTX_RHANDX, //149 
 MNET_BODY_FRONT_IN_CHESTY_RHANDY, //150 
 MNET_BODY_FRONT_IN_CHESTX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //151 
 MNET_BODY_FRONT_IN_CHESTY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //152 
 MNET_BODY_FRONT_IN_CHESTX_LSHOULDERX, //153 
 MNET_BODY_FRONT_IN_CHESTY_LSHOULDERY, //154 
 MNET_BODY_FRONT_IN_CHESTX_LELBOWX, //155 
 MNET_BODY_FRONT_IN_CHESTY_LELBOWY, //156 
 MNET_BODY_FRONT_IN_CHESTX_LHANDX, //157 
 MNET_BODY_FRONT_IN_CHESTY_LHANDY, //158 
 MNET_BODY_FRONT_IN_CHESTX_RHIPX, //159 
 MNET_BODY_FRONT_IN_CHESTY_RHIPY, //160 
 MNET_BODY_FRONT_IN_CHESTX_RKNEEX, //161 
 MNET_BODY_FRONT_IN_CHESTY_RKNEEY, //162 
 MNET_BODY_FRONT_IN_CHESTX_RFOOTX, //163 
 MNET_BODY_FRONT_IN_CHESTY_RFOOTY, //164 
 MNET_BODY_FRONT_IN_CHESTX_LHIPX, //165 
 MNET_BODY_FRONT_IN_CHESTY_LHIPY, //166 
 MNET_BODY_FRONT_IN_CHESTX_LKNEEX, //167 
 MNET_BODY_FRONT_IN_CHESTY_LKNEEY, //168 
 MNET_BODY_FRONT_IN_CHESTX_LFOOTX, //169 
 MNET_BODY_FRONT_IN_CHESTY_LFOOTY, //170 
 MNET_BODY_FRONT_IN_NECKX_HIPX, //171 
 MNET_BODY_FRONT_IN_NECKY_HIPY, //172 
 MNET_BODY_FRONT_IN_NECKX_ABDOMENX, //173 
 MNET_BODY_FRONT_IN_NECKY_ABDOMENY, //174 
 MNET_BODY_FRONT_IN_NECKX_CHESTX, //175 
 MNET_BODY_FRONT_IN_NECKY_CHESTY, //176 
 MNET_BODY_FRONT_IN_NECKX_NECKX, //177 
 MNET_BODY_FRONT_IN_NECKY_NECKY, //178 
 MNET_BODY_FRONT_IN_NECKX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //179 
 MNET_BODY_FRONT_IN_NECKY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //180 
 MNET_BODY_FRONT_IN_NECKX_RSHOULDERX, //181 
 MNET_BODY_FRONT_IN_NECKY_RSHOULDERY, //182 
 MNET_BODY_FRONT_IN_NECKX_RELBOWX, //183 
 MNET_BODY_FRONT_IN_NECKY_RELBOWY, //184 
 MNET_BODY_FRONT_IN_NECKX_RHANDX, //185 
 MNET_BODY_FRONT_IN_NECKY_RHANDY, //186 
 MNET_BODY_FRONT_IN_NECKX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //187 
 MNET_BODY_FRONT_IN_NECKY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //188 
 MNET_BODY_FRONT_IN_NECKX_LSHOULDERX, //189 
 MNET_BODY_FRONT_IN_NECKY_LSHOULDERY, //190 
 MNET_BODY_FRONT_IN_NECKX_LELBOWX, //191 
 MNET_BODY_FRONT_IN_NECKY_LELBOWY, //192 
 MNET_BODY_FRONT_IN_NECKX_LHANDX, //193 
 MNET_BODY_FRONT_IN_NECKY_LHANDY, //194 
 MNET_BODY_FRONT_IN_NECKX_RHIPX, //195 
 MNET_BODY_FRONT_IN_NECKY_RHIPY, //196 
 MNET_BODY_FRONT_IN_NECKX_RKNEEX, //197 
 MNET_BODY_FRONT_IN_NECKY_RKNEEY, //198 
 MNET_BODY_FRONT_IN_NECKX_RFOOTX, //199 
 MNET_BODY_FRONT_IN_NECKY_RFOOTY, //200 
 MNET_BODY_FRONT_IN_NECKX_LHIPX, //201 
 MNET_BODY_FRONT_IN_NECKY_LHIPY, //202 
 MNET_BODY_FRONT_IN_NECKX_LKNEEX, //203 
 MNET_BODY_FRONT_IN_NECKY_LKNEEY, //204 
 MNET_BODY_FRONT_IN_NECKX_LFOOTX, //205 
 MNET_BODY_FRONT_IN_NECKY_LFOOTY, //206 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_HIPX, //207 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_HIPY, //208 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_ABDOMENX, //209 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_ABDOMENY, //210 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_CHESTX, //211 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_CHESTY, //212 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_NECKX, //213 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_NECKY, //214 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //215 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //216 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RSHOULDERX, //217 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RSHOULDERY, //218 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RELBOWX, //219 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RELBOWY, //220 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RHANDX, //221 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RHANDY, //222 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //223 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //224 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LSHOULDERX, //225 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LSHOULDERY, //226 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LELBOWX, //227 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LELBOWY, //228 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LHANDX, //229 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LHANDY, //230 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RHIPX, //231 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RHIPY, //232 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RKNEEX, //233 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RKNEEY, //234 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_RFOOTX, //235 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_RFOOTY, //236 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LHIPX, //237 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LHIPY, //238 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LKNEEX, //239 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LKNEEY, //240 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0X_LFOOTX, //241 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_PLUS0_3_Y_0Y_LFOOTY, //242 
 MNET_BODY_FRONT_IN_RSHOULDERX_HIPX, //243 
 MNET_BODY_FRONT_IN_RSHOULDERY_HIPY, //244 
 MNET_BODY_FRONT_IN_RSHOULDERX_ABDOMENX, //245 
 MNET_BODY_FRONT_IN_RSHOULDERY_ABDOMENY, //246 
 MNET_BODY_FRONT_IN_RSHOULDERX_CHESTX, //247 
 MNET_BODY_FRONT_IN_RSHOULDERY_CHESTY, //248 
 MNET_BODY_FRONT_IN_RSHOULDERX_NECKX, //249 
 MNET_BODY_FRONT_IN_RSHOULDERY_NECKY, //250 
 MNET_BODY_FRONT_IN_RSHOULDERX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //251 
 MNET_BODY_FRONT_IN_RSHOULDERY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //252 
 MNET_BODY_FRONT_IN_RSHOULDERX_RSHOULDERX, //253 
 MNET_BODY_FRONT_IN_RSHOULDERY_RSHOULDERY, //254 
 MNET_BODY_FRONT_IN_RSHOULDERX_RELBOWX, //255 
 MNET_BODY_FRONT_IN_RSHOULDERY_RELBOWY, //256 
 MNET_BODY_FRONT_IN_RSHOULDERX_RHANDX, //257 
 MNET_BODY_FRONT_IN_RSHOULDERY_RHANDY, //258 
 MNET_BODY_FRONT_IN_RSHOULDERX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //259 
 MNET_BODY_FRONT_IN_RSHOULDERY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //260 
 MNET_BODY_FRONT_IN_RSHOULDERX_LSHOULDERX, //261 
 MNET_BODY_FRONT_IN_RSHOULDERY_LSHOULDERY, //262 
 MNET_BODY_FRONT_IN_RSHOULDERX_LELBOWX, //263 
 MNET_BODY_FRONT_IN_RSHOULDERY_LELBOWY, //264 
 MNET_BODY_FRONT_IN_RSHOULDERX_LHANDX, //265 
 MNET_BODY_FRONT_IN_RSHOULDERY_LHANDY, //266 
 MNET_BODY_FRONT_IN_RSHOULDERX_RHIPX, //267 
 MNET_BODY_FRONT_IN_RSHOULDERY_RHIPY, //268 
 MNET_BODY_FRONT_IN_RSHOULDERX_RKNEEX, //269 
 MNET_BODY_FRONT_IN_RSHOULDERY_RKNEEY, //270 
 MNET_BODY_FRONT_IN_RSHOULDERX_RFOOTX, //271 
 MNET_BODY_FRONT_IN_RSHOULDERY_RFOOTY, //272 
 MNET_BODY_FRONT_IN_RSHOULDERX_LHIPX, //273 
 MNET_BODY_FRONT_IN_RSHOULDERY_LHIPY, //274 
 MNET_BODY_FRONT_IN_RSHOULDERX_LKNEEX, //275 
 MNET_BODY_FRONT_IN_RSHOULDERY_LKNEEY, //276 
 MNET_BODY_FRONT_IN_RSHOULDERX_LFOOTX, //277 
 MNET_BODY_FRONT_IN_RSHOULDERY_LFOOTY, //278 
 MNET_BODY_FRONT_IN_RELBOWX_HIPX, //279 
 MNET_BODY_FRONT_IN_RELBOWY_HIPY, //280 
 MNET_BODY_FRONT_IN_RELBOWX_ABDOMENX, //281 
 MNET_BODY_FRONT_IN_RELBOWY_ABDOMENY, //282 
 MNET_BODY_FRONT_IN_RELBOWX_CHESTX, //283 
 MNET_BODY_FRONT_IN_RELBOWY_CHESTY, //284 
 MNET_BODY_FRONT_IN_RELBOWX_NECKX, //285 
 MNET_BODY_FRONT_IN_RELBOWY_NECKY, //286 
 MNET_BODY_FRONT_IN_RELBOWX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //287 
 MNET_BODY_FRONT_IN_RELBOWY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //288 
 MNET_BODY_FRONT_IN_RELBOWX_RSHOULDERX, //289 
 MNET_BODY_FRONT_IN_RELBOWY_RSHOULDERY, //290 
 MNET_BODY_FRONT_IN_RELBOWX_RELBOWX, //291 
 MNET_BODY_FRONT_IN_RELBOWY_RELBOWY, //292 
 MNET_BODY_FRONT_IN_RELBOWX_RHANDX, //293 
 MNET_BODY_FRONT_IN_RELBOWY_RHANDY, //294 
 MNET_BODY_FRONT_IN_RELBOWX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //295 
 MNET_BODY_FRONT_IN_RELBOWY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //296 
 MNET_BODY_FRONT_IN_RELBOWX_LSHOULDERX, //297 
 MNET_BODY_FRONT_IN_RELBOWY_LSHOULDERY, //298 
 MNET_BODY_FRONT_IN_RELBOWX_LELBOWX, //299 
 MNET_BODY_FRONT_IN_RELBOWY_LELBOWY, //300 
 MNET_BODY_FRONT_IN_RELBOWX_LHANDX, //301 
 MNET_BODY_FRONT_IN_RELBOWY_LHANDY, //302 
 MNET_BODY_FRONT_IN_RELBOWX_RHIPX, //303 
 MNET_BODY_FRONT_IN_RELBOWY_RHIPY, //304 
 MNET_BODY_FRONT_IN_RELBOWX_RKNEEX, //305 
 MNET_BODY_FRONT_IN_RELBOWY_RKNEEY, //306 
 MNET_BODY_FRONT_IN_RELBOWX_RFOOTX, //307 
 MNET_BODY_FRONT_IN_RELBOWY_RFOOTY, //308 
 MNET_BODY_FRONT_IN_RELBOWX_LHIPX, //309 
 MNET_BODY_FRONT_IN_RELBOWY_LHIPY, //310 
 MNET_BODY_FRONT_IN_RELBOWX_LKNEEX, //311 
 MNET_BODY_FRONT_IN_RELBOWY_LKNEEY, //312 
 MNET_BODY_FRONT_IN_RELBOWX_LFOOTX, //313 
 MNET_BODY_FRONT_IN_RELBOWY_LFOOTY, //314 
 MNET_BODY_FRONT_IN_RHANDX_HIPX, //315 
 MNET_BODY_FRONT_IN_RHANDY_HIPY, //316 
 MNET_BODY_FRONT_IN_RHANDX_ABDOMENX, //317 
 MNET_BODY_FRONT_IN_RHANDY_ABDOMENY, //318 
 MNET_BODY_FRONT_IN_RHANDX_CHESTX, //319 
 MNET_BODY_FRONT_IN_RHANDY_CHESTY, //320 
 MNET_BODY_FRONT_IN_RHANDX_NECKX, //321 
 MNET_BODY_FRONT_IN_RHANDY_NECKY, //322 
 MNET_BODY_FRONT_IN_RHANDX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //323 
 MNET_BODY_FRONT_IN_RHANDY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //324 
 MNET_BODY_FRONT_IN_RHANDX_RSHOULDERX, //325 
 MNET_BODY_FRONT_IN_RHANDY_RSHOULDERY, //326 
 MNET_BODY_FRONT_IN_RHANDX_RELBOWX, //327 
 MNET_BODY_FRONT_IN_RHANDY_RELBOWY, //328 
 MNET_BODY_FRONT_IN_RHANDX_RHANDX, //329 
 MNET_BODY_FRONT_IN_RHANDY_RHANDY, //330 
 MNET_BODY_FRONT_IN_RHANDX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //331 
 MNET_BODY_FRONT_IN_RHANDY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //332 
 MNET_BODY_FRONT_IN_RHANDX_LSHOULDERX, //333 
 MNET_BODY_FRONT_IN_RHANDY_LSHOULDERY, //334 
 MNET_BODY_FRONT_IN_RHANDX_LELBOWX, //335 
 MNET_BODY_FRONT_IN_RHANDY_LELBOWY, //336 
 MNET_BODY_FRONT_IN_RHANDX_LHANDX, //337 
 MNET_BODY_FRONT_IN_RHANDY_LHANDY, //338 
 MNET_BODY_FRONT_IN_RHANDX_RHIPX, //339 
 MNET_BODY_FRONT_IN_RHANDY_RHIPY, //340 
 MNET_BODY_FRONT_IN_RHANDX_RKNEEX, //341 
 MNET_BODY_FRONT_IN_RHANDY_RKNEEY, //342 
 MNET_BODY_FRONT_IN_RHANDX_RFOOTX, //343 
 MNET_BODY_FRONT_IN_RHANDY_RFOOTY, //344 
 MNET_BODY_FRONT_IN_RHANDX_LHIPX, //345 
 MNET_BODY_FRONT_IN_RHANDY_LHIPY, //346 
 MNET_BODY_FRONT_IN_RHANDX_LKNEEX, //347 
 MNET_BODY_FRONT_IN_RHANDY_LKNEEY, //348 
 MNET_BODY_FRONT_IN_RHANDX_LFOOTX, //349 
 MNET_BODY_FRONT_IN_RHANDY_LFOOTY, //350 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_HIPX, //351 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_HIPY, //352 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_ABDOMENX, //353 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_ABDOMENY, //354 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_CHESTX, //355 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_CHESTY, //356 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_NECKX, //357 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_NECKY, //358 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //359 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //360 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RSHOULDERX, //361 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RSHOULDERY, //362 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RELBOWX, //363 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RELBOWY, //364 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RHANDX, //365 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RHANDY, //366 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //367 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //368 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LSHOULDERX, //369 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LSHOULDERY, //370 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LELBOWX, //371 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LELBOWY, //372 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LHANDX, //373 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LHANDY, //374 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RHIPX, //375 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RHIPY, //376 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RKNEEX, //377 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RKNEEY, //378 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_RFOOTX, //379 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_RFOOTY, //380 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LHIPX, //381 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LHIPY, //382 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LKNEEX, //383 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LKNEEY, //384 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0X_LFOOTX, //385 
 MNET_BODY_FRONT_IN_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y_LFOOTY, //386 
 MNET_BODY_FRONT_IN_LSHOULDERX_HIPX, //387 
 MNET_BODY_FRONT_IN_LSHOULDERY_HIPY, //388 
 MNET_BODY_FRONT_IN_LSHOULDERX_ABDOMENX, //389 
 MNET_BODY_FRONT_IN_LSHOULDERY_ABDOMENY, //390 
 MNET_BODY_FRONT_IN_LSHOULDERX_CHESTX, //391 
 MNET_BODY_FRONT_IN_LSHOULDERY_CHESTY, //392 
 MNET_BODY_FRONT_IN_LSHOULDERX_NECKX, //393 
 MNET_BODY_FRONT_IN_LSHOULDERY_NECKY, //394 
 MNET_BODY_FRONT_IN_LSHOULDERX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //395 
 MNET_BODY_FRONT_IN_LSHOULDERY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //396 
 MNET_BODY_FRONT_IN_LSHOULDERX_RSHOULDERX, //397 
 MNET_BODY_FRONT_IN_LSHOULDERY_RSHOULDERY, //398 
 MNET_BODY_FRONT_IN_LSHOULDERX_RELBOWX, //399 
 MNET_BODY_FRONT_IN_LSHOULDERY_RELBOWY, //400 
 MNET_BODY_FRONT_IN_LSHOULDERX_RHANDX, //401 
 MNET_BODY_FRONT_IN_LSHOULDERY_RHANDY, //402 
 MNET_BODY_FRONT_IN_LSHOULDERX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //403 
 MNET_BODY_FRONT_IN_LSHOULDERY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //404 
 MNET_BODY_FRONT_IN_LSHOULDERX_LSHOULDERX, //405 
 MNET_BODY_FRONT_IN_LSHOULDERY_LSHOULDERY, //406 
 MNET_BODY_FRONT_IN_LSHOULDERX_LELBOWX, //407 
 MNET_BODY_FRONT_IN_LSHOULDERY_LELBOWY, //408 
 MNET_BODY_FRONT_IN_LSHOULDERX_LHANDX, //409 
 MNET_BODY_FRONT_IN_LSHOULDERY_LHANDY, //410 
 MNET_BODY_FRONT_IN_LSHOULDERX_RHIPX, //411 
 MNET_BODY_FRONT_IN_LSHOULDERY_RHIPY, //412 
 MNET_BODY_FRONT_IN_LSHOULDERX_RKNEEX, //413 
 MNET_BODY_FRONT_IN_LSHOULDERY_RKNEEY, //414 
 MNET_BODY_FRONT_IN_LSHOULDERX_RFOOTX, //415 
 MNET_BODY_FRONT_IN_LSHOULDERY_RFOOTY, //416 
 MNET_BODY_FRONT_IN_LSHOULDERX_LHIPX, //417 
 MNET_BODY_FRONT_IN_LSHOULDERY_LHIPY, //418 
 MNET_BODY_FRONT_IN_LSHOULDERX_LKNEEX, //419 
 MNET_BODY_FRONT_IN_LSHOULDERY_LKNEEY, //420 
 MNET_BODY_FRONT_IN_LSHOULDERX_LFOOTX, //421 
 MNET_BODY_FRONT_IN_LSHOULDERY_LFOOTY, //422 
 MNET_BODY_FRONT_IN_LELBOWX_HIPX, //423 
 MNET_BODY_FRONT_IN_LELBOWY_HIPY, //424 
 MNET_BODY_FRONT_IN_LELBOWX_ABDOMENX, //425 
 MNET_BODY_FRONT_IN_LELBOWY_ABDOMENY, //426 
 MNET_BODY_FRONT_IN_LELBOWX_CHESTX, //427 
 MNET_BODY_FRONT_IN_LELBOWY_CHESTY, //428 
 MNET_BODY_FRONT_IN_LELBOWX_NECKX, //429 
 MNET_BODY_FRONT_IN_LELBOWY_NECKY, //430 
 MNET_BODY_FRONT_IN_LELBOWX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //431 
 MNET_BODY_FRONT_IN_LELBOWY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //432 
 MNET_BODY_FRONT_IN_LELBOWX_RSHOULDERX, //433 
 MNET_BODY_FRONT_IN_LELBOWY_RSHOULDERY, //434 
 MNET_BODY_FRONT_IN_LELBOWX_RELBOWX, //435 
 MNET_BODY_FRONT_IN_LELBOWY_RELBOWY, //436 
 MNET_BODY_FRONT_IN_LELBOWX_RHANDX, //437 
 MNET_BODY_FRONT_IN_LELBOWY_RHANDY, //438 
 MNET_BODY_FRONT_IN_LELBOWX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //439 
 MNET_BODY_FRONT_IN_LELBOWY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //440 
 MNET_BODY_FRONT_IN_LELBOWX_LSHOULDERX, //441 
 MNET_BODY_FRONT_IN_LELBOWY_LSHOULDERY, //442 
 MNET_BODY_FRONT_IN_LELBOWX_LELBOWX, //443 
 MNET_BODY_FRONT_IN_LELBOWY_LELBOWY, //444 
 MNET_BODY_FRONT_IN_LELBOWX_LHANDX, //445 
 MNET_BODY_FRONT_IN_LELBOWY_LHANDY, //446 
 MNET_BODY_FRONT_IN_LELBOWX_RHIPX, //447 
 MNET_BODY_FRONT_IN_LELBOWY_RHIPY, //448 
 MNET_BODY_FRONT_IN_LELBOWX_RKNEEX, //449 
 MNET_BODY_FRONT_IN_LELBOWY_RKNEEY, //450 
 MNET_BODY_FRONT_IN_LELBOWX_RFOOTX, //451 
 MNET_BODY_FRONT_IN_LELBOWY_RFOOTY, //452 
 MNET_BODY_FRONT_IN_LELBOWX_LHIPX, //453 
 MNET_BODY_FRONT_IN_LELBOWY_LHIPY, //454 
 MNET_BODY_FRONT_IN_LELBOWX_LKNEEX, //455 
 MNET_BODY_FRONT_IN_LELBOWY_LKNEEY, //456 
 MNET_BODY_FRONT_IN_LELBOWX_LFOOTX, //457 
 MNET_BODY_FRONT_IN_LELBOWY_LFOOTY, //458 
 MNET_BODY_FRONT_IN_LHANDX_HIPX, //459 
 MNET_BODY_FRONT_IN_LHANDY_HIPY, //460 
 MNET_BODY_FRONT_IN_LHANDX_ABDOMENX, //461 
 MNET_BODY_FRONT_IN_LHANDY_ABDOMENY, //462 
 MNET_BODY_FRONT_IN_LHANDX_CHESTX, //463 
 MNET_BODY_FRONT_IN_LHANDY_CHESTY, //464 
 MNET_BODY_FRONT_IN_LHANDX_NECKX, //465 
 MNET_BODY_FRONT_IN_LHANDY_NECKY, //466 
 MNET_BODY_FRONT_IN_LHANDX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //467 
 MNET_BODY_FRONT_IN_LHANDY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //468 
 MNET_BODY_FRONT_IN_LHANDX_RSHOULDERX, //469 
 MNET_BODY_FRONT_IN_LHANDY_RSHOULDERY, //470 
 MNET_BODY_FRONT_IN_LHANDX_RELBOWX, //471 
 MNET_BODY_FRONT_IN_LHANDY_RELBOWY, //472 
 MNET_BODY_FRONT_IN_LHANDX_RHANDX, //473 
 MNET_BODY_FRONT_IN_LHANDY_RHANDY, //474 
 MNET_BODY_FRONT_IN_LHANDX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //475 
 MNET_BODY_FRONT_IN_LHANDY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //476 
 MNET_BODY_FRONT_IN_LHANDX_LSHOULDERX, //477 
 MNET_BODY_FRONT_IN_LHANDY_LSHOULDERY, //478 
 MNET_BODY_FRONT_IN_LHANDX_LELBOWX, //479 
 MNET_BODY_FRONT_IN_LHANDY_LELBOWY, //480 
 MNET_BODY_FRONT_IN_LHANDX_LHANDX, //481 
 MNET_BODY_FRONT_IN_LHANDY_LHANDY, //482 
 MNET_BODY_FRONT_IN_LHANDX_RHIPX, //483 
 MNET_BODY_FRONT_IN_LHANDY_RHIPY, //484 
 MNET_BODY_FRONT_IN_LHANDX_RKNEEX, //485 
 MNET_BODY_FRONT_IN_LHANDY_RKNEEY, //486 
 MNET_BODY_FRONT_IN_LHANDX_RFOOTX, //487 
 MNET_BODY_FRONT_IN_LHANDY_RFOOTY, //488 
 MNET_BODY_FRONT_IN_LHANDX_LHIPX, //489 
 MNET_BODY_FRONT_IN_LHANDY_LHIPY, //490 
 MNET_BODY_FRONT_IN_LHANDX_LKNEEX, //491 
 MNET_BODY_FRONT_IN_LHANDY_LKNEEY, //492 
 MNET_BODY_FRONT_IN_LHANDX_LFOOTX, //493 
 MNET_BODY_FRONT_IN_LHANDY_LFOOTY, //494 
 MNET_BODY_FRONT_IN_RHIPX_HIPX, //495 
 MNET_BODY_FRONT_IN_RHIPY_HIPY, //496 
 MNET_BODY_FRONT_IN_RHIPX_ABDOMENX, //497 
 MNET_BODY_FRONT_IN_RHIPY_ABDOMENY, //498 
 MNET_BODY_FRONT_IN_RHIPX_CHESTX, //499 
 MNET_BODY_FRONT_IN_RHIPY_CHESTY, //500 
 MNET_BODY_FRONT_IN_RHIPX_NECKX, //501 
 MNET_BODY_FRONT_IN_RHIPY_NECKY, //502 
 MNET_BODY_FRONT_IN_RHIPX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //503 
 MNET_BODY_FRONT_IN_RHIPY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //504 
 MNET_BODY_FRONT_IN_RHIPX_RSHOULDERX, //505 
 MNET_BODY_FRONT_IN_RHIPY_RSHOULDERY, //506 
 MNET_BODY_FRONT_IN_RHIPX_RELBOWX, //507 
 MNET_BODY_FRONT_IN_RHIPY_RELBOWY, //508 
 MNET_BODY_FRONT_IN_RHIPX_RHANDX, //509 
 MNET_BODY_FRONT_IN_RHIPY_RHANDY, //510 
 MNET_BODY_FRONT_IN_RHIPX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //511 
 MNET_BODY_FRONT_IN_RHIPY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //512 
 MNET_BODY_FRONT_IN_RHIPX_LSHOULDERX, //513 
 MNET_BODY_FRONT_IN_RHIPY_LSHOULDERY, //514 
 MNET_BODY_FRONT_IN_RHIPX_LELBOWX, //515 
 MNET_BODY_FRONT_IN_RHIPY_LELBOWY, //516 
 MNET_BODY_FRONT_IN_RHIPX_LHANDX, //517 
 MNET_BODY_FRONT_IN_RHIPY_LHANDY, //518 
 MNET_BODY_FRONT_IN_RHIPX_RHIPX, //519 
 MNET_BODY_FRONT_IN_RHIPY_RHIPY, //520 
 MNET_BODY_FRONT_IN_RHIPX_RKNEEX, //521 
 MNET_BODY_FRONT_IN_RHIPY_RKNEEY, //522 
 MNET_BODY_FRONT_IN_RHIPX_RFOOTX, //523 
 MNET_BODY_FRONT_IN_RHIPY_RFOOTY, //524 
 MNET_BODY_FRONT_IN_RHIPX_LHIPX, //525 
 MNET_BODY_FRONT_IN_RHIPY_LHIPY, //526 
 MNET_BODY_FRONT_IN_RHIPX_LKNEEX, //527 
 MNET_BODY_FRONT_IN_RHIPY_LKNEEY, //528 
 MNET_BODY_FRONT_IN_RHIPX_LFOOTX, //529 
 MNET_BODY_FRONT_IN_RHIPY_LFOOTY, //530 
 MNET_BODY_FRONT_IN_RKNEEX_HIPX, //531 
 MNET_BODY_FRONT_IN_RKNEEY_HIPY, //532 
 MNET_BODY_FRONT_IN_RKNEEX_ABDOMENX, //533 
 MNET_BODY_FRONT_IN_RKNEEY_ABDOMENY, //534 
 MNET_BODY_FRONT_IN_RKNEEX_CHESTX, //535 
 MNET_BODY_FRONT_IN_RKNEEY_CHESTY, //536 
 MNET_BODY_FRONT_IN_RKNEEX_NECKX, //537 
 MNET_BODY_FRONT_IN_RKNEEY_NECKY, //538 
 MNET_BODY_FRONT_IN_RKNEEX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //539 
 MNET_BODY_FRONT_IN_RKNEEY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //540 
 MNET_BODY_FRONT_IN_RKNEEX_RSHOULDERX, //541 
 MNET_BODY_FRONT_IN_RKNEEY_RSHOULDERY, //542 
 MNET_BODY_FRONT_IN_RKNEEX_RELBOWX, //543 
 MNET_BODY_FRONT_IN_RKNEEY_RELBOWY, //544 
 MNET_BODY_FRONT_IN_RKNEEX_RHANDX, //545 
 MNET_BODY_FRONT_IN_RKNEEY_RHANDY, //546 
 MNET_BODY_FRONT_IN_RKNEEX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //547 
 MNET_BODY_FRONT_IN_RKNEEY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //548 
 MNET_BODY_FRONT_IN_RKNEEX_LSHOULDERX, //549 
 MNET_BODY_FRONT_IN_RKNEEY_LSHOULDERY, //550 
 MNET_BODY_FRONT_IN_RKNEEX_LELBOWX, //551 
 MNET_BODY_FRONT_IN_RKNEEY_LELBOWY, //552 
 MNET_BODY_FRONT_IN_RKNEEX_LHANDX, //553 
 MNET_BODY_FRONT_IN_RKNEEY_LHANDY, //554 
 MNET_BODY_FRONT_IN_RKNEEX_RHIPX, //555 
 MNET_BODY_FRONT_IN_RKNEEY_RHIPY, //556 
 MNET_BODY_FRONT_IN_RKNEEX_RKNEEX, //557 
 MNET_BODY_FRONT_IN_RKNEEY_RKNEEY, //558 
 MNET_BODY_FRONT_IN_RKNEEX_RFOOTX, //559 
 MNET_BODY_FRONT_IN_RKNEEY_RFOOTY, //560 
 MNET_BODY_FRONT_IN_RKNEEX_LHIPX, //561 
 MNET_BODY_FRONT_IN_RKNEEY_LHIPY, //562 
 MNET_BODY_FRONT_IN_RKNEEX_LKNEEX, //563 
 MNET_BODY_FRONT_IN_RKNEEY_LKNEEY, //564 
 MNET_BODY_FRONT_IN_RKNEEX_LFOOTX, //565 
 MNET_BODY_FRONT_IN_RKNEEY_LFOOTY, //566 
 MNET_BODY_FRONT_IN_RFOOTX_HIPX, //567 
 MNET_BODY_FRONT_IN_RFOOTY_HIPY, //568 
 MNET_BODY_FRONT_IN_RFOOTX_ABDOMENX, //569 
 MNET_BODY_FRONT_IN_RFOOTY_ABDOMENY, //570 
 MNET_BODY_FRONT_IN_RFOOTX_CHESTX, //571 
 MNET_BODY_FRONT_IN_RFOOTY_CHESTY, //572 
 MNET_BODY_FRONT_IN_RFOOTX_NECKX, //573 
 MNET_BODY_FRONT_IN_RFOOTY_NECKY, //574 
 MNET_BODY_FRONT_IN_RFOOTX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //575 
 MNET_BODY_FRONT_IN_RFOOTY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //576 
 MNET_BODY_FRONT_IN_RFOOTX_RSHOULDERX, //577 
 MNET_BODY_FRONT_IN_RFOOTY_RSHOULDERY, //578 
 MNET_BODY_FRONT_IN_RFOOTX_RELBOWX, //579 
 MNET_BODY_FRONT_IN_RFOOTY_RELBOWY, //580 
 MNET_BODY_FRONT_IN_RFOOTX_RHANDX, //581 
 MNET_BODY_FRONT_IN_RFOOTY_RHANDY, //582 
 MNET_BODY_FRONT_IN_RFOOTX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //583 
 MNET_BODY_FRONT_IN_RFOOTY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //584 
 MNET_BODY_FRONT_IN_RFOOTX_LSHOULDERX, //585 
 MNET_BODY_FRONT_IN_RFOOTY_LSHOULDERY, //586 
 MNET_BODY_FRONT_IN_RFOOTX_LELBOWX, //587 
 MNET_BODY_FRONT_IN_RFOOTY_LELBOWY, //588 
 MNET_BODY_FRONT_IN_RFOOTX_LHANDX, //589 
 MNET_BODY_FRONT_IN_RFOOTY_LHANDY, //590 
 MNET_BODY_FRONT_IN_RFOOTX_RHIPX, //591 
 MNET_BODY_FRONT_IN_RFOOTY_RHIPY, //592 
 MNET_BODY_FRONT_IN_RFOOTX_RKNEEX, //593 
 MNET_BODY_FRONT_IN_RFOOTY_RKNEEY, //594 
 MNET_BODY_FRONT_IN_RFOOTX_RFOOTX, //595 
 MNET_BODY_FRONT_IN_RFOOTY_RFOOTY, //596 
 MNET_BODY_FRONT_IN_RFOOTX_LHIPX, //597 
 MNET_BODY_FRONT_IN_RFOOTY_LHIPY, //598 
 MNET_BODY_FRONT_IN_RFOOTX_LKNEEX, //599 
 MNET_BODY_FRONT_IN_RFOOTY_LKNEEY, //600 
 MNET_BODY_FRONT_IN_RFOOTX_LFOOTX, //601 
 MNET_BODY_FRONT_IN_RFOOTY_LFOOTY, //602 
 MNET_BODY_FRONT_IN_LHIPX_HIPX, //603 
 MNET_BODY_FRONT_IN_LHIPY_HIPY, //604 
 MNET_BODY_FRONT_IN_LHIPX_ABDOMENX, //605 
 MNET_BODY_FRONT_IN_LHIPY_ABDOMENY, //606 
 MNET_BODY_FRONT_IN_LHIPX_CHESTX, //607 
 MNET_BODY_FRONT_IN_LHIPY_CHESTY, //608 
 MNET_BODY_FRONT_IN_LHIPX_NECKX, //609 
 MNET_BODY_FRONT_IN_LHIPY_NECKY, //610 
 MNET_BODY_FRONT_IN_LHIPX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //611 
 MNET_BODY_FRONT_IN_LHIPY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //612 
 MNET_BODY_FRONT_IN_LHIPX_RSHOULDERX, //613 
 MNET_BODY_FRONT_IN_LHIPY_RSHOULDERY, //614 
 MNET_BODY_FRONT_IN_LHIPX_RELBOWX, //615 
 MNET_BODY_FRONT_IN_LHIPY_RELBOWY, //616 
 MNET_BODY_FRONT_IN_LHIPX_RHANDX, //617 
 MNET_BODY_FRONT_IN_LHIPY_RHANDY, //618 
 MNET_BODY_FRONT_IN_LHIPX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //619 
 MNET_BODY_FRONT_IN_LHIPY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //620 
 MNET_BODY_FRONT_IN_LHIPX_LSHOULDERX, //621 
 MNET_BODY_FRONT_IN_LHIPY_LSHOULDERY, //622 
 MNET_BODY_FRONT_IN_LHIPX_LELBOWX, //623 
 MNET_BODY_FRONT_IN_LHIPY_LELBOWY, //624 
 MNET_BODY_FRONT_IN_LHIPX_LHANDX, //625 
 MNET_BODY_FRONT_IN_LHIPY_LHANDY, //626 
 MNET_BODY_FRONT_IN_LHIPX_RHIPX, //627 
 MNET_BODY_FRONT_IN_LHIPY_RHIPY, //628 
 MNET_BODY_FRONT_IN_LHIPX_RKNEEX, //629 
 MNET_BODY_FRONT_IN_LHIPY_RKNEEY, //630 
 MNET_BODY_FRONT_IN_LHIPX_RFOOTX, //631 
 MNET_BODY_FRONT_IN_LHIPY_RFOOTY, //632 
 MNET_BODY_FRONT_IN_LHIPX_LHIPX, //633 
 MNET_BODY_FRONT_IN_LHIPY_LHIPY, //634 
 MNET_BODY_FRONT_IN_LHIPX_LKNEEX, //635 
 MNET_BODY_FRONT_IN_LHIPY_LKNEEY, //636 
 MNET_BODY_FRONT_IN_LHIPX_LFOOTX, //637 
 MNET_BODY_FRONT_IN_LHIPY_LFOOTY, //638 
 MNET_BODY_FRONT_IN_LKNEEX_HIPX, //639 
 MNET_BODY_FRONT_IN_LKNEEY_HIPY, //640 
 MNET_BODY_FRONT_IN_LKNEEX_ABDOMENX, //641 
 MNET_BODY_FRONT_IN_LKNEEY_ABDOMENY, //642 
 MNET_BODY_FRONT_IN_LKNEEX_CHESTX, //643 
 MNET_BODY_FRONT_IN_LKNEEY_CHESTY, //644 
 MNET_BODY_FRONT_IN_LKNEEX_NECKX, //645 
 MNET_BODY_FRONT_IN_LKNEEY_NECKY, //646 
 MNET_BODY_FRONT_IN_LKNEEX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //647 
 MNET_BODY_FRONT_IN_LKNEEY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //648 
 MNET_BODY_FRONT_IN_LKNEEX_RSHOULDERX, //649 
 MNET_BODY_FRONT_IN_LKNEEY_RSHOULDERY, //650 
 MNET_BODY_FRONT_IN_LKNEEX_RELBOWX, //651 
 MNET_BODY_FRONT_IN_LKNEEY_RELBOWY, //652 
 MNET_BODY_FRONT_IN_LKNEEX_RHANDX, //653 
 MNET_BODY_FRONT_IN_LKNEEY_RHANDY, //654 
 MNET_BODY_FRONT_IN_LKNEEX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //655 
 MNET_BODY_FRONT_IN_LKNEEY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //656 
 MNET_BODY_FRONT_IN_LKNEEX_LSHOULDERX, //657 
 MNET_BODY_FRONT_IN_LKNEEY_LSHOULDERY, //658 
 MNET_BODY_FRONT_IN_LKNEEX_LELBOWX, //659 
 MNET_BODY_FRONT_IN_LKNEEY_LELBOWY, //660 
 MNET_BODY_FRONT_IN_LKNEEX_LHANDX, //661 
 MNET_BODY_FRONT_IN_LKNEEY_LHANDY, //662 
 MNET_BODY_FRONT_IN_LKNEEX_RHIPX, //663 
 MNET_BODY_FRONT_IN_LKNEEY_RHIPY, //664 
 MNET_BODY_FRONT_IN_LKNEEX_RKNEEX, //665 
 MNET_BODY_FRONT_IN_LKNEEY_RKNEEY, //666 
 MNET_BODY_FRONT_IN_LKNEEX_RFOOTX, //667 
 MNET_BODY_FRONT_IN_LKNEEY_RFOOTY, //668 
 MNET_BODY_FRONT_IN_LKNEEX_LHIPX, //669 
 MNET_BODY_FRONT_IN_LKNEEY_LHIPY, //670 
 MNET_BODY_FRONT_IN_LKNEEX_LKNEEX, //671 
 MNET_BODY_FRONT_IN_LKNEEY_LKNEEY, //672 
 MNET_BODY_FRONT_IN_LKNEEX_LFOOTX, //673 
 MNET_BODY_FRONT_IN_LKNEEY_LFOOTY, //674 
 MNET_BODY_FRONT_IN_LFOOTX_HIPX, //675 
 MNET_BODY_FRONT_IN_LFOOTY_HIPY, //676 
 MNET_BODY_FRONT_IN_LFOOTX_ABDOMENX, //677 
 MNET_BODY_FRONT_IN_LFOOTY_ABDOMENY, //678 
 MNET_BODY_FRONT_IN_LFOOTX_CHESTX, //679 
 MNET_BODY_FRONT_IN_LFOOTY_CHESTY, //680 
 MNET_BODY_FRONT_IN_LFOOTX_NECKX, //681 
 MNET_BODY_FRONT_IN_LFOOTY_NECKY, //682 
 MNET_BODY_FRONT_IN_LFOOTX_VIRTUAL_HIP_X_PLUS0_3_Y_0X, //683 
 MNET_BODY_FRONT_IN_LFOOTY_VIRTUAL_HIP_X_PLUS0_3_Y_0Y, //684 
 MNET_BODY_FRONT_IN_LFOOTX_RSHOULDERX, //685 
 MNET_BODY_FRONT_IN_LFOOTY_RSHOULDERY, //686 
 MNET_BODY_FRONT_IN_LFOOTX_RELBOWX, //687 
 MNET_BODY_FRONT_IN_LFOOTY_RELBOWY, //688 
 MNET_BODY_FRONT_IN_LFOOTX_RHANDX, //689 
 MNET_BODY_FRONT_IN_LFOOTY_RHANDY, //690 
 MNET_BODY_FRONT_IN_LFOOTX_VIRTUAL_HIP_X_MINUS_0_3_Y_0X, //691 
 MNET_BODY_FRONT_IN_LFOOTY_VIRTUAL_HIP_X_MINUS_0_3_Y_0Y, //692 
 MNET_BODY_FRONT_IN_LFOOTX_LSHOULDERX, //693 
 MNET_BODY_FRONT_IN_LFOOTY_LSHOULDERY, //694 
 MNET_BODY_FRONT_IN_LFOOTX_LELBOWX, //695 
 MNET_BODY_FRONT_IN_LFOOTY_LELBOWY, //696 
 MNET_BODY_FRONT_IN_LFOOTX_LHANDX, //697 
 MNET_BODY_FRONT_IN_LFOOTY_LHANDY, //698 
 MNET_BODY_FRONT_IN_LFOOTX_RHIPX, //699 
 MNET_BODY_FRONT_IN_LFOOTY_RHIPY, //700 
 MNET_BODY_FRONT_IN_LFOOTX_RKNEEX, //701 
 MNET_BODY_FRONT_IN_LFOOTY_RKNEEY, //702 
 MNET_BODY_FRONT_IN_LFOOTX_RFOOTX, //703 
 MNET_BODY_FRONT_IN_LFOOTY_RFOOTY, //704 
 MNET_BODY_FRONT_IN_LFOOTX_LHIPX, //705 
 MNET_BODY_FRONT_IN_LFOOTY_LHIPY, //706 
 MNET_BODY_FRONT_IN_LFOOTX_LKNEEX, //707 
 MNET_BODY_FRONT_IN_LFOOTY_LKNEEY, //708 
 MNET_BODY_FRONT_IN_LFOOTX_LFOOTX, //709 
 MNET_BODY_FRONT_IN_LFOOTY_LFOOTY, //710 
 MNET_BODY_FRONT_IN_NUMBER
};

enum mocapNET_NSDM_body_front 
{
 MNET_NSDM_BODY_FRONT_hip, //0 
 MNET_NSDM_BODY_FRONT_abdomen, //1 
 MNET_NSDM_BODY_FRONT_chest, //2 
 MNET_NSDM_BODY_FRONT_neck, //3 
 MNET_NSDM_BODY_FRONT_virtual_hip_x_plus0_3_y_0, //4 
 MNET_NSDM_BODY_FRONT_rshoulder, //5 
 MNET_NSDM_BODY_FRONT_relbow, //6 
 MNET_NSDM_BODY_FRONT_rhand, //7 
 MNET_NSDM_BODY_FRONT_virtual_hip_x_minus_0_3_y_0, //8 
 MNET_NSDM_BODY_FRONT_lshoulder, //9 
 MNET_NSDM_BODY_FRONT_lelbow, //10 
 MNET_NSDM_BODY_FRONT_lhand, //11 
 MNET_NSDM_BODY_FRONT_rhip, //12 
 MNET_NSDM_BODY_FRONT_rknee, //13 
 MNET_NSDM_BODY_FRONT_rfoot, //14 
 MNET_NSDM_BODY_FRONT_lhip, //15 
 MNET_NSDM_BODY_FRONT_lknee, //16 
 MNET_NSDM_BODY_FRONT_lfoot, //17 
 MNET_NSDM_BODY_FRONT_NUMBER
};

static const int mocapNET_ResolveJoint_body_front[] = 
{
 0, //0 
 1, //1 
 2, //2 
 3, //3 
 0, //4 
 6, //5 
 7, //6 
 8, //7 
 0, //8 
 10, //9 
 11, //10 
 12, //11 
 13, //12 
 14, //13 
 15, //14 
 17, //15 
 18, //16 
 19, //17 
 0//end of array
};

static const int mocapNET_ArtificialJoint_body_front[] = 
{
 0, //0 
 0, //1 
 0, //2 
 0, //3 
 1, //4 
 0, //5 
 0, //6 
 0, //7 
 1, //8 
 0, //9 
 0, //10 
 0, //11 
 0, //12 
 0, //13 
 0, //14 
 0, //15 
 0, //16 
 0, //17 
 0//end of array
};

static const float mocapNET_ArtificialJointXOffset_body_front[] = 
{
 0, //0 
 0, //1 
 0, //2 
 0, //3 
 0.3, //4 
 0, //5 
 0, //6 
 0, //7 
 -0.3, //8 
 0, //9 
 0, //10 
 0, //11 
 0, //12 
 0, //13 
 0, //14 
 0, //15 
 0, //16 
 0, //17 
 0//end of array
};

static const float mocapNET_ArtificialJointYOffset_body_front[] = 
{
 0, //0 
 0, //1 
 0, //2 
 0, //3 
 0, //4 
 0, //5 
 0, //6 
 0, //7 
 0, //8 
 0, //9 
 0, //10 
 0, //11 
 0, //12 
 0, //13 
 0, //14 
 0, //15 
 0, //16 
 0, //17 
 0//end of array
};

static const float mocapNET_ScalingStart_body_front[] = 
{
 0, //0 
 0, //1 
 0//end of array
};

static const float mocapNET_ScalingEnd_body_front[] = 
{
 6, //0 
 10, //1 
 0//end of array
};

static float getJoint2DDistance_BODY_FRONT(std::vector<float> in,int jointA,int jointB)
 {
    float aX=in[jointA*3+0];
    float aY=in[jointA*3+1];
    float bX=in[jointB*3+0];
    float bY=in[jointB*3+1];
    if ( (aX==0) || (aY==0) || (bX==0) || (bY==0) )
        {return 0.0;}
    return sqrt( ((bX-aX)*(bX-aX)) + ((bY-aY)*(bY-aY)) );
 }

static std::vector<float> body_frontCreateNDSM(std::vector<float> in)
 {
    std::vector<float> result;
    for (int i=0; i<MNET_NSDM_BODY_FRONT_NUMBER; i++)
    {
     unsigned int iJointID=mocapNET_ResolveJoint_body_front[i];
     unsigned int iX=in[iJointID*3+0];
     unsigned int iY=in[iJointID*3+1];
     unsigned int iVisibility=in[iJointID*3+2];
     for (int j=0; j<MNET_NSDM_BODY_FRONT_NUMBER; j++)
     {
       unsigned int jJointID=mocapNET_ResolveJoint_body_front[j];
       unsigned int jX=in[jJointID*3+0];
       unsigned int jY=in[jJointID*3+1];
       unsigned int jVisibility=in[jJointID*3+2];
       if ( (iX==0) || (iY==0) || (jX==0) || (jY==0) ) 
       { result.push_back(0.0); result.push_back(0.0); }
       else
       {
       if (mocapNET_ArtificialJoint_body_front[i])
          {
           iX+=mocapNET_ArtificialJointXOffset_body_front[i];
           iY+=mocapNET_ArtificialJointYOffset_body_front[i];
          }
       if (mocapNET_ArtificialJoint_body_front[j])
          {
           jX+=mocapNET_ArtificialJointXOffset_body_front[j];
           jY+=mocapNET_ArtificialJointYOffset_body_front[j];
          }
       result.push_back(iX-jX);
       result.push_back(iY-jY);

       }
     }
    }
  //Normalization
  unsigned int numberOfNSDMScalingRules=2;
      if (numberOfNSDMScalingRules>0)
        {
         unsigned int numberOfDistanceSamples=0;
         float sumOfDistanceSamples=0.0;
         for ( int i=0; i<numberOfNSDMScalingRules; i++) 
            {
             unsigned int iJointID=mocapNET_ScalingStart_body_front[i];
             unsigned int jJointID=mocapNET_ScalingEnd_body_front[i];
             float distance = getJoint2DDistance_BODY_FRONT(in,iJointID,jJointID);
             if (distance>0.0)
               {
                numberOfDistanceSamples=numberOfDistanceSamples+1;
                sumOfDistanceSamples=sumOfDistanceSamples+distance;
               }
            }
//------------------------------------------------------------------------------------------------- 
        float scaleDistance=1.0;
//------------------------------------------------------------------------------------------------- 
        if (numberOfDistanceSamples>0)
            { scaleDistance=sumOfDistanceSamples/numberOfDistanceSamples; }
//-------------------------------------------------------------------------------------------------
        if (scaleDistance!=1.0)
            {
             for (int i=0; i<result.size(); i++)
                  { result[i]=result[i]/scaleDistance; } 
            }
//-------------------------------------------------------------------------------------------------
       for (int i=0; i<result.size(); i++)
            {
              if (result[i]!=0.0)
                { result[i]=0.5+result[i]; }
            }
//-------------------------------------------------------------------------------------------------
          }
 return result;
 }
